learn_user/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('dang-ki/',views.registration,name='dang-ki'),
    path('dang-nhap/',views.user_login,name='dang-nhap'),
]

learn_user/learn_user/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
from basic_app import urls as BasicUrl
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",views.index,name='index'),
    path('dang-xuat/',views.user_logout,name='log-out'),
    path('special/',views.special,name='special'),
    path("admin/", admin.site.urls),
    path(f'{BasicUrl.app_name}/',include('basic_app.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learn_user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    #addional field
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username
    
    
    

learn_user/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(),label='Mật khẩu')
    username = forms.CharField(label='Tên người dùng')
    email = forms.EmailField(label='Email')

    class Meta():
        model=User
        fields=('username','email','password')

class UserFrofileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learn_user/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserFrofileInfoForm
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context_dict={
        'title':'Trang chủ'
    }

    return render(request,'basic_app/index.html',context=context_dict)

def registration(request):
    registered=False
    user_form = UserForm()
    profile_form = UserFrofileInfoForm()
    
    if request.method=='POST':
        user_form=UserForm(request.POST)
        profile_form = UserFrofileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            try:
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user=user

                if 'profile_pic' in request.FILES:
                    profile.profile_pic = request.FILES['profile_pic']
                    # im = Image.open(request.FILES['profile_pic'])
                    # im.save() 

                profile.save()

                registered=True
                user_form = UserForm()
                profile_form = UserFrofileInfoForm()
            except NameError:
                print(NameError)

        else:
            print(user_form.errors,profile_form.errors)

    context_dict={
        'title':'Đăng kí',
        'user_form' :user_form,
        'profile_form':profile_form,
        'registered':registered,
    }

    return render(request,'basic_app/registration.html',context=context_dict)

def user_login(request):
    if request.method=='POST':
        print('Iam here ',request)
        username=request.POST.get('username')
        password=request.POST.get('password')
        rememberMe=request.POST.get('rememberMe')

        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                if not rememberMe:
                    # <-- Here if the remember me is False, 
                    # that is why expiry is set to 0 seconds. 
                    # So it will automatically close the session after the browser is closed.
                    request.session.set_expiry(0)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS ACTIVE")
        else:
            print('Login Failed')
            return HttpResponse("Login failed")

    context_dict={
        'title':'Đăng nhập',
        # 'user':user,
    }
    
    return render(request,'basic_app/login.html',context=context_dict)

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    print("Log out")
    logout(request)

    return HttpResponseRedirect(reverse('index'))

learn_user/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <!--<link-->
    <!--  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"-->
    <!--  rel="stylesheet"-->
    <!--  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"-->
    <!--  crossorigin="anonymous"-->
    <!--/>-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <button
          class="navbar-toggler d-lg-none"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapsibleNavId"
          aria-controls="collapsibleNavId"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav me-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}"
                >Home <span class="visually-hidden">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:dang-ki' %}"
                >Registration</a
              >
            </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'log-out' %}"
                    >Logout</a
                  >
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic_app:dang-nhap' %}"
                    >Login</a
                  >
                </li>
            {% endif %}
          </ul>
          {% comment %} <form class="d-flex my-2 my-lg-0">
            <input
              class="form-control me-sm-2"
              type="text"
              placeholder="Search"
            />
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
              Search
            </button>
          </form> {% endcomment %}
          {% if user.is_authenticated %}
            <span class='text-white'>Xin chào <strong>{{user.username}}</strong></span>
          {% else %}
            <form class="d-flex my-2 my-lg-0">
              <input
                class="form-control me-sm-2"
                type="text"
                placeholder="Search"
              />
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                Search
              </button>
            </form>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">{% block body_block %}{% endblock %}</div>
  </body>
</html>

{% block lastScript %}{% endblock lastScript %}

learn_user/templates/basic_app/index.html
{% extends 'basic_app/base.html' %} {% block body_block %}
<div class="p-5 bg-warning">
  <div class="container">
    <h1 class="display-3 fw-bold">Trang chủ</h1>
    <p class="lead">Jumbo helper text</p>
    <hr class="my-2" />
    <p>More info</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button"
        >Jumbo action name</a
      >
    </p>
  </div>
</div>

{% endblock %}

learn_user/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <div class="row justify-content-center align-content-center" style='height: 100%'>
        <form class='row col-md-6 justify-content-center p-5 bg-light mt-4 rounded-4 shadow' method='post'>
            <div class="form-group mb-3 px-0 ">
                <label for="inputEmail" class='fw-bold'>Tên đăng nhập</label>
                <input type="text" class="form-control" id="username" name='username' placeholder="Email">
            </div>
            <div class="form-group mb-3 px-0">
                <label for="inputPassword" class='fw-bold'>Mật khẩu</label>
                <input type="password" class="form-control" id="inputPassword" placeholder="Password" name='password'>
            </div>
            <div class="form-group mb-3">
                <label class="form-check-label"><input type="checkbox" name='rememberMe'> Remember me</label>
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
            </div>
            {% csrf_token %}
        </form>
{% endblock body_block %}

learn_user/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
{% if registered %}
    <div class="p-5 bg-success">
            <h1 class="display-3 text-white">Thank you for registering!</h1>
    </div>
{% else %}
    <form action="" method="post" enctype='multipart/form-data' id='form_registration'>
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endif %}
{% endblock body_block %}

{% block lastScript %}
<script>
  var element = document.getElementById("form_registration");
  if (element){
    element.classList = "p-5 bg-white row col-md-6";
    for (let i of element.children) {
      if (i.tagName == "P") {
        i.classList = "mb-3 px-0";
        i.children[0].classList = "form-label fw-bold";
        i.children[1].classList = "form-control";
      } else if (i.tagName == "BUTTON") {
        i.classList = "btn btn-primary col-6";
      }
    }
    for (let item of document.getElementsByClassName('errorlist')){
      item.classList.add('text-danger')
    }
  }
</script>
{% endblock lastScript %}